spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 320925
    url: jdbc:mysql://localhost:3306/mooc?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
#server:
#  context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
